/*
 * AlphaBot 2 API
 * API for interacting with an AlphaBot 2 RasPi
 *
 * OpenAPI spec version: 1.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {LEDState} from './LEDState';

/**
 * The AlphaBotLEDs model module.
 * @module model/AlphaBotLEDs
 * @version 1.0.2
 */
export class AlphaBotLEDs {
  /**
   * Constructs a new <code>AlphaBotLEDs</code>.
   * State of the four AlphaBot 2 LEDs on the bottom.
   * @alias module:model/AlphaBotLEDs
   * @class
   * @param lED1 {module:model/LEDState} 
   * @param lED2 {module:model/LEDState} 
   * @param lED3 {module:model/LEDState} 
   * @param lED4 {module:model/LEDState} 
   */
  constructor(lED1, lED2, lED3, lED4) {
    this.lED1 = lED1;
    this.lED2 = lED2;
    this.lED3 = lED3;
    this.lED4 = lED4;
  }

  /**
   * Constructs a <code>AlphaBotLEDs</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AlphaBotLEDs} obj Optional instance to populate.
   * @return {module:model/AlphaBotLEDs} The populated <code>AlphaBotLEDs</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AlphaBotLEDs();
      if (data.hasOwnProperty('LED1'))
        obj.lED1 = LEDState.constructFromObject(data['LED1']);
      if (data.hasOwnProperty('LED2'))
        obj.lED2 = LEDState.constructFromObject(data['LED2']);
      if (data.hasOwnProperty('LED3'))
        obj.lED3 = LEDState.constructFromObject(data['LED3']);
      if (data.hasOwnProperty('LED4'))
        obj.lED4 = LEDState.constructFromObject(data['LED4']);
    }
    return obj;
  }
}

/**
 * @member {module:model/LEDState} lED1
 */
AlphaBotLEDs.prototype.lED1 = undefined;

/**
 * @member {module:model/LEDState} lED2
 */
AlphaBotLEDs.prototype.lED2 = undefined;

/**
 * @member {module:model/LEDState} lED3
 */
AlphaBotLEDs.prototype.lED3 = undefined;

/**
 * @member {module:model/LEDState} lED4
 */
AlphaBotLEDs.prototype.lED4 = undefined;

