/*
 * AlphaBot 2 API
 * API for interacting with an AlphaBot 2 RasPi
 *
 * OpenAPI spec version: 1.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The BottomSensors model module.
 * @module model/BottomSensors
 * @version 1.0.2
 */
export class BottomSensors {
  /**
   * Constructs a new <code>BottomSensors</code>.
   * Values from bottom infrared sensors.
   * @alias module:model/BottomSensors
   * @class
   * @param iR1 {Number} 
   * @param iR2 {Number} 
   * @param iR3 {Number} 
   * @param iR4 {Number} 
   * @param iR5 {Number} 
   */
  constructor(iR1, iR2, iR3, iR4, iR5) {
    this.iR1 = iR1;
    this.iR2 = iR2;
    this.iR3 = iR3;
    this.iR4 = iR4;
    this.iR5 = iR5;
  }

  /**
   * Constructs a <code>BottomSensors</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BottomSensors} obj Optional instance to populate.
   * @return {module:model/BottomSensors} The populated <code>BottomSensors</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BottomSensors();
      if (data.hasOwnProperty('IR1'))
        obj.iR1 = ApiClient.convertToType(data['IR1'], 'Number');
      if (data.hasOwnProperty('IR2'))
        obj.iR2 = ApiClient.convertToType(data['IR2'], 'Number');
      if (data.hasOwnProperty('IR3'))
        obj.iR3 = ApiClient.convertToType(data['IR3'], 'Number');
      if (data.hasOwnProperty('IR4'))
        obj.iR4 = ApiClient.convertToType(data['IR4'], 'Number');
      if (data.hasOwnProperty('IR5'))
        obj.iR5 = ApiClient.convertToType(data['IR5'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} iR1
 */
BottomSensors.prototype.iR1 = undefined;

/**
 * @member {Number} iR2
 */
BottomSensors.prototype.iR2 = undefined;

/**
 * @member {Number} iR3
 */
BottomSensors.prototype.iR3 = undefined;

/**
 * @member {Number} iR4
 */
BottomSensors.prototype.iR4 = undefined;

/**
 * @member {Number} iR5
 */
BottomSensors.prototype.iR5 = undefined;

