/*
 * AlphaBot 2 API
 * API for interacting with an AlphaBot 2 RasPi
 *
 * OpenAPI spec version: 1.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Color model module.
 * @module model/Color
 * @version 1.0.2
 */
export class Color {
  /**
   * Constructs a new <code>Color</code>.
   * RGB Color.
   * @alias module:model/Color
   * @class
   * @param red {Number} 
   * @param blue {Number} 
   * @param green {Number} 
   */
  constructor(red, blue, green) {
    this.red = red;
    this.blue = blue;
    this.green = green;
  }

  /**
   * Constructs a <code>Color</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Color} obj Optional instance to populate.
   * @return {module:model/Color} The populated <code>Color</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Color();
      if (data.hasOwnProperty('Red'))
        obj.red = ApiClient.convertToType(data['Red'], 'Number');
      if (data.hasOwnProperty('Blue'))
        obj.blue = ApiClient.convertToType(data['Blue'], 'Number');
      if (data.hasOwnProperty('Green'))
        obj.green = ApiClient.convertToType(data['Green'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} red
 */
Color.prototype.red = undefined;

/**
 * @member {Number} blue
 */
Color.prototype.blue = undefined;

/**
 * @member {Number} green
 */
Color.prototype.green = undefined;

