/*
 * AlphaBot 2 API
 * API for interacting with an AlphaBot 2 RasPi
 *
 * OpenAPI spec version: 1.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class Direction.
 * @enum {String}
 * @readonly
 */
const Direction = {
  /**
   * value: "forward"
   * @const
   */
  forward: "forward",

  /**
   * value: "backward"
   * @const
   */
  backward: "backward",

  /**
   * value: "left"
   * @const
   */
  left: "left",

  /**
   * value: "right"
   * @const
   */
  right: "right",

  /**
   * Returns a <code>Direction</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/Direction} The enum <code>Direction</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {Direction};