/*
 * AlphaBot 2 API
 * API for interacting with an AlphaBot 2 RasPi
 *
 * OpenAPI spec version: 1.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DistanceMeasurementResult model module.
 * @module model/DistanceMeasurementResult
 * @version 1.0.2
 */
export class DistanceMeasurementResult {
  /**
   * Constructs a new <code>DistanceMeasurementResult</code>.
   * Result of a distance measurement.
   * @alias module:model/DistanceMeasurementResult
   * @class
   * @param distance {Number} Distance in cm.
   */
  constructor(distance) {
    this.distance = distance;
  }

  /**
   * Constructs a <code>DistanceMeasurementResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DistanceMeasurementResult} obj Optional instance to populate.
   * @return {module:model/DistanceMeasurementResult} The populated <code>DistanceMeasurementResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DistanceMeasurementResult();
      if (data.hasOwnProperty('distance'))
        obj.distance = ApiClient.convertToType(data['distance'], 'Number');
    }
    return obj;
  }
}

/**
 * Distance in cm.
 * @member {Number} distance
 */
DistanceMeasurementResult.prototype.distance = undefined;

