/*
 * AlphaBot 2 API
 * API for interacting with an AlphaBot 2 RasPi
 *
 * OpenAPI spec version: 1.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ObstaclesDetectionResult model module.
 * @module model/ObstaclesDetectionResult
 * @version 1.0.2
 */
export class ObstaclesDetectionResult {
  /**
   * Constructs a new <code>ObstaclesDetectionResult</code>.
   * Result of a obstacles detection.
   * @alias module:model/ObstaclesDetectionResult
   * @class
   * @param detectedOnLeft {Boolean} This property is true if a obstacle on the left was detected.
   * @param detectedOnRight {Boolean} This property is true if a obstacle on the left was detected.
   */
  constructor(detectedOnLeft, detectedOnRight) {
    this.detectedOnLeft = detectedOnLeft;
    this.detectedOnRight = detectedOnRight;
  }

  /**
   * Constructs a <code>ObstaclesDetectionResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ObstaclesDetectionResult} obj Optional instance to populate.
   * @return {module:model/ObstaclesDetectionResult} The populated <code>ObstaclesDetectionResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ObstaclesDetectionResult();
      if (data.hasOwnProperty('detectedOnLeft'))
        obj.detectedOnLeft = ApiClient.convertToType(data['detectedOnLeft'], 'Boolean');
      if (data.hasOwnProperty('detectedOnRight'))
        obj.detectedOnRight = ApiClient.convertToType(data['detectedOnRight'], 'Boolean');
    }
    return obj;
  }
}

/**
 * This property is true if a obstacle on the left was detected.
 * @member {Boolean} detectedOnLeft
 */
ObstaclesDetectionResult.prototype.detectedOnLeft = undefined;

/**
 * This property is true if a obstacle on the left was detected.
 * @member {Boolean} detectedOnRight
 */
ObstaclesDetectionResult.prototype.detectedOnRight = undefined;

