/*
 * AlphaBot 2 API
 * API for interacting with an AlphaBot 2 RasPi
 *
 * OpenAPI spec version: 1.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {AlphaBotLEDs} from './model/AlphaBotLEDs';
import {BottomSensors} from './model/BottomSensors';
import {CameraDirection} from './model/CameraDirection';
import {Color} from './model/Color';
import {Direction} from './model/Direction';
import {DistanceMeasurementResult} from './model/DistanceMeasurementResult';
import {LEDState} from './model/LEDState';
import {ObstaclesDetectionResult} from './model/ObstaclesDetectionResult';
import {LEDsApi} from './api/LEDsApi';
import {MoveApi} from './api/MoveApi';
import {SensorsApi} from './api/SensorsApi';

/**
* API_for_interacting_with_an_AlphaBot_2_RasPi.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var AlphaBot2Api = require('index'); // See note below*.
* var xxxSvc = new AlphaBot2Api.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new AlphaBot2Api.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new AlphaBot2Api.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new AlphaBot2Api.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.2
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AlphaBotLEDs model constructor.
     * @property {module:model/AlphaBotLEDs}
     */
    AlphaBotLEDs,

    /**
     * The BottomSensors model constructor.
     * @property {module:model/BottomSensors}
     */
    BottomSensors,

    /**
     * The CameraDirection model constructor.
     * @property {module:model/CameraDirection}
     */
    CameraDirection,

    /**
     * The Color model constructor.
     * @property {module:model/Color}
     */
    Color,

    /**
     * The Direction model constructor.
     * @property {module:model/Direction}
     */
    Direction,

    /**
     * The DistanceMeasurementResult model constructor.
     * @property {module:model/DistanceMeasurementResult}
     */
    DistanceMeasurementResult,

    /**
     * The LEDState model constructor.
     * @property {module:model/LEDState}
     */
    LEDState,

    /**
     * The ObstaclesDetectionResult model constructor.
     * @property {module:model/ObstaclesDetectionResult}
     */
    ObstaclesDetectionResult,

    /**
    * The LEDsApi service constructor.
    * @property {module:api/LEDsApi}
    */
    LEDsApi,

    /**
    * The MoveApi service constructor.
    * @property {module:api/MoveApi}
    */
    MoveApi,

    /**
    * The SensorsApi service constructor.
    * @property {module:api/SensorsApi}
    */
    SensorsApi
};
