/*
 * AlphaBot 2 API
 * API for interacting with an AlphaBot 2 RasPi
 *
 * OpenAPI spec version: 1.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {LEDState} from '../model/LEDState';

/**
* LEDs service.
* @module api/LEDsApi
* @version 1.0.2
*/
export class LEDsApi {

    /**
    * Constructs a new LEDsApi. 
    * @alias module:api/LEDsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the setAllLEDs operation.
     * @callback moduleapi/LEDsApi~setAllLEDsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Sets all four LEDs of the AlphaBot 2.
     * @param {Object} opts Optional parameters
     * @param {module:model/LEDState} opts.lED1 
     * @param {module:model/LEDState} opts.lED2 
     * @param {module:model/LEDState} opts.lED3 
     * @param {module:model/LEDState} opts.lED4 
     * @param {module:api/LEDsApi~setAllLEDsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    setAllLEDs(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        'LED1': opts['lED1'],'LED2': opts['lED2'],'LED3': opts['lED3'],'LED4': opts['lED4']
      };

      let authNames = [];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/led/setAll', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}